:kaomoji:
  - #================================
    :aa:  !str  (｡>﹏<)あㄘ”ゅいー
    :txt: !str  あつい
  - #================================
    :aa:  !str  （´◉◞౪◟◉)
    :txt: !str  あひゃ
  - #================================
    :aa:  !str  ＜：コミ
    :txt: !str  いか
  - #================================
    :aa:  !str  (=ﾟωﾟ)ﾉぃょぅ
    :txt: !str  いよう
  - #================================
    :aa:  !str  (ﾟ⊿ﾟ)ｲﾗﾈ
    :txt: !str  いらね
  - #================================
    :aa:  !str  ( 0w0)ノ ｳｪｰｲ
    :txt: !str  うぇーい
  - #================================
    :aa:  !str  ζ*'ヮ')ζうっうー
    :txt: !str  うっうー
  - #================================
    :aa:  !str  ぅゎょぅι゛ょっょぃ
    :txt: !str  うわようじょつよい
  - #================================
    :aa:  !str  (´･ω｀･)ｴｯ?
    :txt: !str  えっ
  - #================================
    :aa:  !str  (○´ω｀○)ゞｴﾍﾍ
    :txt: !str  えへへ
  - #================================
    :aa:  !str  ٩(๑`н´๑)۶
    :txt: !str  おこ
  - #================================
    :aa:  !str  (　 ﾟДﾟ)⊃旦 < 茶飲め
    :txt: !str  おちゃ
  - #================================
    :aa:  !str  （＾ω＾≡＾ω＾）
    :txt: !str  おっ
  - #================================
    :aa:  !str  (｀・ω・´)ゞ
    :txt: !str  おつ
  - #================================
    :aa:  !str  (# ﾟДﾟ)㌦ｧ!!
    :txt: !str  おらぁ
  - #================================
    :aa:  !str  (# ﾟДﾟ)㌦ｧ!!
    :txt: !str  おらあ
  - #================================
    :aa:  !str  (・∀・)カエレ!!
    :txt: !str  かえれ
  - #================================
    :aa:  !str  （「・ω・）「
    :txt: !str  がおー
  - #================================
    :aa:  !str  (((( ；ﾟДﾟ)))ｶﾞｸｶﾞｸﾌﾞﾙﾌﾞﾙ
    :txt: !str  がくぶる
  - #================================
    :aa:  !str  ｷﾀ━(ﾟ∀ﾟ)━!
    :txt: !str  きたー
  - #================================
    :aa:  !str  ☆ゝω・)vｷｬﾋﾟ
    :txt: !str  きゃぴ
  - #================================
    :aa:  !str  (ｷﾘｯ
    :txt: !str  きりっ
  - #================================
    :aa:  !str  （´-`）.｡oO（）
    :txt: !str  くうそう
  - #================================
    :aa:  !str  (๑˃̵ᴗ˂̵)و
    :txt: !str  ぐっ
  - #================================
    :aa:  !str  ( ᐛ )و
    :txt: !str  ぐっ
  - #================================
    :aa:  !str  (*Ծ﹏Ծ)ぐぬぬ
    :txt: !str  ぐぬぬ
  - #================================
    :aa:  !str  (# ﾟДﾟ)㌦ｧ!!
    :txt: !str  ごらぁ
  - #================================
    :aa:  !str  (# ﾟДﾟ)㌦ｧ!!
    :txt: !str  ごらあ
  - #================================
    :aa:  !str  (# ﾟДﾟ)㌦ｧ!!
    :txt: !str  ごるぁ
  - #================================
    :aa:  !str  (# ﾟДﾟ)㌦ｧ!!
    :txt: !str  ごるあ
  - #================================
    :aa:  !str  (｀･ω･´)ゞ
    :txt: !str  しゃきーん
  - #================================
    :aa:  !str  (٥﹏٥` )
    :txt: !str  しゅん
  - #================================
    :aa:  !str  (´・ω・`)ｼｮﾎﾞｰﾝ
    :txt: !str  しょぼーん
  - #================================
    :aa:  !str  (ﾟ⊿ﾟ)シﾗﾈ
    :txt: !str  しらね
  - #================================
    :aa:  !str  ヽ^ｼ▰╹ヮ╹)ﾉｼ
    :txt: !str  じたばた
  - #================================
    :aa:  !str  ( ˘ω˘ ) ｽﾔｧ…
    :txt: !str  すやあ
  - #================================
    :aa:  !str  するよ！ ＞ ('(ﾟ∀ﾟ∩
    :txt: !str  するよ
  - #================================
    :aa:  !str  ｽﾞｲ₍₍ (ง ˘ω˘ )ว ⁾⁾ｽﾞｲ
    :txt: !str  ずいずい
  - #================================
    :aa:  !str  c⌒っﾟДﾟ)っ
    :txt: !str  ずさー
  - #================================
    :aa:  !str  （◞‸◟）そっか…
    :txt: !str  そっか
  - #================================
    :aa:  !str  ✌('ω'✌ )三✌('ω')✌三( ✌'ω')✌
    :txt: !str  たのしい
  - #================================
    :aa:  !str  (　 ﾟДﾟ)⊃旦 < 茶飲め
    :txt: !str  ちゃのめ
  - #================================
    :aa:  !str  (/ω・＼)ﾁﾗｯ
    :txt: !str  ちらっ
  - #================================
    :aa:  !str  (ﾟ⊿ﾟ)ツマンネ
    :txt: !str  つまんね
  - #================================
    :aa:  !str  ( ・_・)σﾞﾂﾝﾂﾝ
    :txt: !str  つんつん
  - #================================
    :aa:  !str  (ﾉ´∀｀*)
    :txt: !str  てれ
  - #================================
    :aa:  !str  (๑╹＿╹)ﾃﾞｰﾝ
    :txt: !str  でーん
  - #================================
    :aa:  !str  (　 ﾟДﾟ)⊃旦
    :txt: !str  どうぞ
  - #================================
    :aa:  !str  (　 ﾟДﾟ)⊃旦
    :txt: !str  どぞー
  - #================================
    :aa:  !str  (　‘◟ ‘)✧
    :txt: !str  どや
  - #================================
    :aa:  !str  (・´－・`)ﾄﾞﾔｧ
    :txt: !str  どやぁ
  - #================================
    :aa:  !str  (ヾﾉ･∀･`)ﾅｲﾅｲ
    :txt: !str  ないない
  - #================================
    :aa:  !str  ヾ(╹◡╹๑)なでなでっ♪
    :txt: !str  なでなで
  - #================================
    :aa:  !str  ヾ(＞ヮ＜*)ﾅﾃﾞﾅﾃﾞ
    :txt: !str  なでなで
  - #================================
    :aa:  !str  （´◉◞౪◟◉)
    :txt: !str  なにか
  - #================================
    :aa:  !str  (๑¯Δ¯๑)/にゃんぱすー
    :txt: !str  にゃんぱす
  - #================================
    :aa:  !str  (っ=﹏=c) .｡o○
    :txt: !str  ねむい
  - #================================
    :aa:  !str  (*´ω｀ *)
    :txt: !str  はやらない
  - #================================
    :aa:  !str  (*´ω｀ *)ﾊﾔﾙ
    :txt: !str  はやる
  - #================================
    :aa:  !str  ੭ु  ◕ ‿‿ ◕ )੭ु⁾⁾
    :txt: !str  ぱたぱた
  - #================================
    :aa:  !str  (　ﾟДﾟ)ﾉﾉ"　ﾊﾟﾊﾟｧﾝ☆彡
    :txt: !str  ぱんぱん
  - #================================
    :aa:        ":;(∩´﹏`∩);:"
    :txt: !str  ふええ
  - #================================
    :aa:  !str  ヾ(｡>﹏<｡)ﾉﾞ
    :txt: !str  ふええ
  - #================================
    :aa:  !str  ｡ﾟ(´っωｃ`)ﾟ｡
    :txt: !str  ふええ
  - #================================
    :aa:  !str  ヾ(｡>◡<)ﾉ"
    :txt: !str  ふりふり
  - #================================
    :aa:  !str  ヾ(oﾟωﾟo)ﾉﾞ
    :txt: !str  ふりふり
  - #================================
    :aa:  !str  (☍﹏⁰)
    :txt: !str  ぶわっ
  - #================================
    :aa:  !str  ( ﾟдﾟ)σ)Д｀)ﾌﾟﾆﾌﾟﾆ
    :txt: !str  ぷにぷに
  - #================================
    :aa:  !str  ヾ(oﾟωﾟo)ﾉﾞ
    :txt: !str  ぷにぷに
  - #================================
    :aa:  !str  o(｀ω´*)oﾌﾟﾝｽｶ！
    :txt: !str  ぷんすか
  - #================================
    :aa:  !str  (m＿ ＿)m
    :txt: !str  ぺこり
  - #================================
    :aa:  !str  (ﾟДﾟ)、ペッ!!
    :txt: !str  ぺっ
  - #================================
    :aa:  !str  ( ﾟдﾟ)ﾎｽｨ…
    :txt: !str  ほしい
  - #================================
    :aa:  !str  ( ﾟдﾟ)ﾎﾟｶｰﾝ
    :txt: !str  ぽかーん
  - #================================
    :aa:  !str  ◝(╹▿╹)◜
    :txt: !str  ぽよ
  - #================================
    :aa:  !str  (•̀﹏•́ )ﾑｽﾞｶｼｨ・・・
    :txt: !str  むずかしい
  - #================================
    :aa:  !str  （´-`）.｡oO（）
    :txt: !str  もうそう
  - #================================
    :aa:  !str  (*´～｀ *)ŧ‹"ŧ‹"ŧ‹"
    :txt: !str  もぐもぐ
  - #================================
    :aa:  !str  ƪ(•◡•ƪ)"ょぃょぃ
    :txt: !str  よいよい
  - #================================
    :aa:  !str  ょぅι゛ょ
    :txt: !str  ようじょ
  - #================================
    :aa:  !str  ( º﹃ º｀ ) 
    :txt: !str  よだれ
  - #================================
    :aa:  !str  (｀･ω･´)ゞ
    :txt: !str  りょ
  - #================================
    :aa:  !str  (｀･ω･´)ゞ
    :txt: !str  りょーかい
